services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mirea
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure

  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=university
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mirea
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: on-failure
    
  neo4j:
    image: neo4j:latest
    container_name: neo
    hostname: neo4j
    environment:
      - NEO4J_AUTH=neo4j/mireamirea
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    restart: on-failure

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elastic
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: on-failure

  kibana:
    image: kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure

  data:
    build:
      context: ./data_center
    depends_on:
      - postgres
      - redis
      - mongodb
      - neo4j
      - elasticsearch
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mirea
      - POSTGRES_DB=university
      - REDIS_HOST=redis
      - MONGODB_HOST=mongodb
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=mirea
      - NEO4J_HOST=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mirea
      - ELASTICSEARCH_HOST=elasticsearch

  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - lab1 
      - lab2
      - lab3
      - data

  lab1:
    build:
      context: ./lab1
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
      - neo4j
      - elasticsearch
      - data
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - NEO4J_HOST=neo4j
      - ELASTICSEARCH_HOST=elasticsearch
  lab2:
    build:
      context: ./lab2
    ports:
      - "8002:8000"
    depends_on:
      - postgres
      - neo4j
      - data
    environment:
      - POSTGRES_HOST=postgres
      - NEO4J_HOST=neo4j

  lab3:
    build:
      context: ./lab3
    ports:
      - "8003:8000"
    depends_on:
      - postgres
      - redis
      - neo4j
      - data
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - NEO4J_HOST=neo4j


volumes:
  postgres_data:
  redis_data:
  mongo_data:
  neo4j_data:
  elasticsearch_data:

